## .travis.yml

language: go

sudo: false

go:
  - "1.16"
  - "1.12"
  - tip
before_install:
  - chmod +x ./.travis.gofmt.sh
script:
  - ./.travis.gofmt.sh
  - go test -v -race $(go list ./... | grep -v vendor)